name: Build_Android_APK

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - uses: meteorengineer/setup-meteor@v1
      with:
        meteor-release: '1.9.1'
    - run: meteor npm install

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: install android sdkmanager
      uses: malinskiy/action-android/install-sdk@release/0.0.5

      

    - name: Run build_android_application.sh to build android apk from meteor project
      run: ./mobile/android/build_android_application.sh

    - uses: actions/upload-artifact@v1
      with:
        name: mobile-build
        path: buildscripts/mobile/android


