name: Build_Android_APK

on:
  push:
    #branches: [ release ]
    tags:
    - 'v*'
  pull_request:
    #branches: [ release ]
    tags:
    - 'v*'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - uses: meteorengineer/setup-meteor@v1
      with:
        meteor-release: '1.9.1'
    - run: meteor npm install

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: install android sdkmanager
      uses: malinskiy/action-android/install-sdk@release/0.0.5

      

    - name: Run build_android_application.sh to build android apk from meteor project
      run: ./mobile/android/build_android_application.sh

    - uses: actions/upload-artifact@v1
      with:
        name: mobile-build
        path: simple-todos/simple-todos_Android_Application
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
    
    - name: Zip folder
      run: zip -r mobile-build.zip simple-todos/simple-todos_Android_Application
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mobile-build.zip 
          asset_name: mobile-build.zip
          asset_content_type: application/zip


