name: Build_Android_APK

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - uses: meteorengineer/setup-meteor@v1
      with:
        meteor-release: '1.9.1'
    - run: meteor npm install

    - name: set up JDK 1.8
    - uses: actions/setup-java@v1
           with:
             java-version: 1.8
    
    - name: install android sdkmanager
    - uses: malinskiy/action-android/install-sdk@release/0.0.5

      

    - name: Run install_android.sh script to install and configure the necessary packages to build android apk  
      run: ./mobile/android/install_android.sh

